spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GIT-CLIENT-ID}
            client-secret: ${GIT-CLIENT-SECRET}
          google:
            client-id: ${GOOGLE-CLIENT-ID}
            client-secret: ${GOOGLE-CLIENT-SECRET}

application:
  security:
    jwt:
      secret-key: gW5D+Z1rM9b5c7I0XAx/8uU4V9G43zU64JfNSiYDZU4=
      expiration: 86400000
      refresh-token:
        expiration: 604800000

logging:
  level:
    org:
      springframework:
        security: trace
